server:
  port: 8080
  servlet:
    context-path: /pawFund
spring:
  datasource:
    url: "jdbc:mysql://localhost:3306/pawfriend"
    username: root
    password: Hcmcity@114
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true